/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Helper;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jaime
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroColumnas = new javax.swing.JTextField();
        txtNumeroFilas = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cmdCrear = new javax.swing.JButton();
        cmdManual = new javax.swing.JButton();
        cmdAutomatico = new javax.swing.JButton();
        cmdOperacion = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTablaInicial = new javax.swing.JTable();
        cmbOperaciones = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtMensaje1 = new javax.swing.JLabel();
        txtMensaje = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRecorrido = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos Iniciales"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("No. de Filas:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel2.setText("No. de Columnas:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtNumeroColumnas.setText("13");
        jPanel2.add(txtNumeroColumnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 80, -1));

        txtNumeroFilas.setText("13");
        txtNumeroFilas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroFilasActionPerformed(evt);
            }
        });
        jPanel2.add(txtNumeroFilas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 80, -1));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 240, 130));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Acciones:"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel3.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, -1));

        cmdManual.setText("Manual");
        cmdManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdManualActionPerformed(evt);
            }
        });
        jPanel3.add(cmdManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 90, -1));

        cmdAutomatico.setText("Automatico");
        cmdAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAutomaticoActionPerformed(evt);
            }
        });
        jPanel3.add(cmdAutomatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        cmdOperacion.setText("Operacion");
        cmdOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOperacionActionPerformed(evt);
            }
        });
        jPanel3.add(cmdOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 90, -1));

        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 100, -1));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 320, 150));

        tblTablaInicial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblTablaInicial);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 360, 240));

        cmbOperaciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Figura 1", "Figura 2", "Figura 3", "Figura 4", "Figura 5" }));
        cmbOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOperacionesActionPerformed(evt);
            }
        });
        jPanel4.add(cmbOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 140, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel3.setText("OPERACIONES CON MATRICES");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        txtMensaje1.setForeground(new java.awt.Color(0, 204, 0));
        txtMensaje1.setText("El numero de filas y columnas deben de ser iguales");
        jPanel4.add(txtMensaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, 20));

        txtMensaje.setForeground(new java.awt.Color(0, 204, 0));
        txtMensaje.setText("Nota: deje 13 en las casillas para que la matriz sea mejor formada, sino editelo");
        jPanel4.add(txtMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, 20));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Recorridos"));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRecorrido.setColumns(20);
        txtRecorrido.setRows(5);
        jScrollPane1.setViewportView(txtRecorrido);

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 740, 50));

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 770, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroFilasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroFilasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroFilasActionPerformed

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
        try {
            int cont = 0;
            if (txtNumeroFilas.getText().trim().isEmpty()) {
                Helper.mensaje(this, "Digite por favor el numero de filas", 1);
                txtNumeroFilas.requestFocusInWindow();
            } else if (Integer.parseInt(txtNumeroFilas.getText()) < 5 || Integer.parseInt(txtNumeroFilas.getText()) > 13) {
                Helper.mensaje(this, "el numero de filas debe mayor a 4 y menor a 14 ", 3);
                txtNumeroFilas.requestFocusInWindow();
                txtNumeroFilas.selectAll();
            } else if (txtNumeroColumnas.getText().trim().isEmpty()) {
                Helper.mensaje(this, "Digite por favor el numero de columnas", 1);
                txtNumeroColumnas.requestFocusInWindow();
            } else if (Integer.parseInt(txtNumeroColumnas.getText()) < 5 || Integer.parseInt(txtNumeroColumnas.getText()) > 13) {
                Helper.mensaje(this, "el numero de columnas debe mayor a 4 y menor a 14 ", 3);
                txtNumeroColumnas.requestFocusInWindow();
                txtNumeroColumnas.selectAll();
            } else if ((Integer.parseInt(txtNumeroFilas.getText())) != (Integer.parseInt(txtNumeroColumnas.getText()))) {
                Helper.mensaje(this, "El numero de filas y columnas deben de ser iguales", 3);
                txtNumeroFilas.requestFocusInWindow();
                txtNumeroFilas.selectAll();
            } else if (Integer.parseInt(txtNumeroFilas.getText()) % 2 == 0) {
                cont++;
                if (cont >= 1) {
                    Helper.mensaje(this, "En esta matriz solo se permite longitudes impares", 3);
                    txtNumeroFilas.requestFocusInWindow();
                    txtNumeroFilas.selectAll();
                }
            } else if (Integer.parseInt(txtNumeroColumnas.getText()) % 2 == 0) {
                cont++;
                if (cont >= 1) {
                    Helper.mensaje(this, "En esta matriz solo se permite longitudes impares", 3);
                    txtNumeroColumnas.requestFocusInWindow();
                    txtNumeroColumnas.selectAll();
                }
            } else {
                DefaultTableModel tm = (DefaultTableModel) tblTablaInicial.getModel();

                int nf = Integer.parseInt(txtNumeroFilas.getText());
                int nc = Integer.parseInt(txtNumeroColumnas.getText());

                tm.setRowCount(nf);
                tm.setColumnCount(nc);

                JButton botonesH[] = {cmdAutomatico, cmdManual, cmdLimpiar};
                JButton botonesD[] = {cmdCrear, cmdOperacion};

                Helper.habilitarBotones(botonesH);
                Helper.deshabilitarBotones(botonesD);
                txtNumeroColumnas.setEditable(false);
                txtNumeroFilas.setEditable(false);
                txtMensaje.setText("");
                txtMensaje1.setText("");
            }

        } catch (NumberFormatException e) {
            Helper.mensaje(this, "Digite un numero valido", 3);

        }
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdManualActionPerformed

        int sw, res, cont = 0;

        int nc = tblTablaInicial.getColumnCount();
        int nf = tblTablaInicial.getRowCount();

        for (int i = 0; i < nf; i++) {
            for (int j = 0; j < nc; j++) {
                do {
                    sw = 1;
                    try {
                        int n = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el elmento en la posición [" + i + "]" + "[" + j + "]", 1).trim());
                        tblTablaInicial.setValueAt(n, i, j);

                    } catch (NumberFormatException e) {
                        Helper.mensaje(this, "Digite un número válido", 3);
                        sw = 0;

                    } catch (NullPointerException e) {
                        res = JOptionPane.showConfirmDialog(this, "¿Seguro que desea salir?", "Salir", JOptionPane.YES_NO_OPTION);
                        if (res == JOptionPane.YES_NO_OPTION) {
                            sw = 1;
                            i = nf;
                            j = nc;
                            cont++;

                        } else {
                            sw = 0;
                        }
                    }
                } while (sw == 0);
            }
        }
        if (cont > 0) {
            JButton botonesH[] = {cmdAutomatico, cmdManual, cmdLimpiar, cmdOperacion};
            JButton botonesD[] = {cmdOperacion, cmdCrear,};

            Helper.habilitarBotones(botonesH);
            Helper.deshabilitarBotones(botonesD);
        } else {
            JButton botonesH[] = {cmdLimpiar, cmdOperacion};
            JButton botonesD[] = {cmdAutomatico, cmdManual, cmdCrear,};

            Helper.habilitarBotones(botonesH);
            Helper.deshabilitarBotones(botonesD);
        }
    }//GEN-LAST:event_cmdManualActionPerformed

    private void cmdAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAutomaticoActionPerformed
        int nf, nc, n;

        nc = tblTablaInicial.getColumnCount();
        nf = tblTablaInicial.getRowCount();

        for (int i = 0; i < nf; i++) {
            for (int j = 0; j < nc; j++) {
                n = (int) (Math.random() * 50 + 1);
                tblTablaInicial.setValueAt(n, i, j);
            }
            JButton botonesH[] = {cmdLimpiar, cmdOperacion};
            JButton botonesD[] = {cmdAutomatico, cmdManual, cmdCrear,};

            Helper.habilitarBotones(botonesH);
            Helper.deshabilitarBotones(botonesD);

        }
    }//GEN-LAST:event_cmdAutomaticoActionPerformed

    private void cmdOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOperacionActionPerformed

        int op = cmbOperaciones.getSelectedIndex();

        switch (op) {
            case 0:
                txtRecorrido.setText(Helper.recorridoUno(tblTablaInicial));
                break;
            case 1:
                txtRecorrido.setText(Helper.recorridoDos(tblTablaInicial));
                break;
            case 2:
                txtRecorrido.setText(Helper.recorridoTres(tblTablaInicial));
                break;
        }
    }//GEN-LAST:event_cmdOperacionActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed

        txtNumeroFilas.setText("13");
        txtNumeroColumnas.setText("13");
        txtMensaje.setText("Nota: deje 13 en las casillas para que la matriz sea mejor formada, sino cambielo");
        txtMensaje1.setText("El numero de filas y columnas deben de ser iguales");
        txtNumeroFilas.selectAll();
        txtNumeroColumnas.selectAll();

        txtNumeroFilas.requestFocusInWindow();
        cmbOperaciones.setSelectedIndex(0);

        Helper.porDefectoTabla(tblTablaInicial);

        JButton botonesH[] = {cmdCrear, cmdLimpiar};
        JButton botonesD[] = {cmdManual, cmdAutomatico, cmdOperacion};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);

        txtNumeroColumnas.setEditable(true);
        txtNumeroFilas.setEditable(true);
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void cmbOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOperacionesActionPerformed

    }//GEN-LAST:event_cmbOperacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbOperaciones;
    private javax.swing.JButton cmdAutomatico;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdManual;
    private javax.swing.JButton cmdOperacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblTablaInicial;
    private javax.swing.JLabel txtMensaje;
    private javax.swing.JLabel txtMensaje1;
    private javax.swing.JTextField txtNumeroColumnas;
    private javax.swing.JTextField txtNumeroFilas;
    private javax.swing.JTextArea txtRecorrido;
    // End of variables declaration//GEN-END:variables
}
